### ISSUE TITLE
Suggestion: ImportCrystalData could take ExternalIdentifier objects

### ISSUE THREAD

**Issue by jasondbiggs** [Stianpr20/MaXrd#10]
These types can be resolved to CIF files

```

ExternalIdentifier["CrystallographyOpenDatabaseID", id : (_Integer | _String)] :> StringTemplate["http://www.crystallography.net/cod/`1`.cif"][id]

ExternalIdentifier["PDBStructureID", id: (_Integer | _String)]   :>  StringTemplate["https://files.rcsb.org/download/`1`.cif.gz"][id]

```
This would allow you to call `ImportCrystalData` when all you have is a database ID - download the CIF file to a temp directory, import the data as usual, the delete the file.

Just a bit of syntactic sugar to save the user from downloading the file themselves.

**Comment by stianpram** [comment]
That is a neat suggestion, thank you! I have overloaded `ImportCrystalData` with a new definition for an `ExternalIdentifier` argument in the commit d9ca0554137b6f836d68767f5e06d1f7f2365c1e.

Usage example:
```Mathematica
demoExtID = ExternalIdentifier["CrystallographyOpenDatabaseID", "9011577"];
ImportCrystalData @ demoExtID
```

Note that you could also use an URL directly:
```Mathematica
ImportCrystalData["http://www.crystallography.net/cod/9011577.cif"]
```

I have not implemented `"PDBStructureID"` since the package does not support macromolecular CIFs.
