### ISSUE TITLE
Is there a way that the MaXrd repository can be put into the $UserBaseDirectory Applications folder instead of using paclet installation?

### ISSUE THREAD

**Issue by sgbaird** [Stianpr20/MaXrd#6]
Interested for command line/compute cluster use.

**Comment by sgbaird** [comment]
I think I got it by just unzipping the .zip file into $UserBaseDirectory/Paclets/Repository

**Comment by stianpram** [comment]
Yes, it should work to put the `MaXrd` directory directly in `$UserBaseDirectory/Applications`. Make sure to use a [built version](https://github.com/Stianpr20/MaXrd/releases) instead of a master/repository copy. You can just unzip it and place the `MaXrd` folder in `$UserBaseDirectory/Applications` and achieve the same «installation» as if you use the front end installation, at least to my knowledge.
